version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Puedes cambiar el puerto según sea necesario
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:   # Cambia esta contraseña
      MYSQL_DATABASE: ventas_php        # Cambia por el nombre de tu base de datos
      MYSQL_USER: root            # Cambia por tu usuario
      MYSQL_PASSWORD:          # Cambia por tu contraseña
    ports:
      - "3306:3306"
