name: Ejecutar Pruebas Automáticas

# Ejecutar flujo de trabajo en cada push o pull request a la rama principal
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    # Define el entorno para ejecutar las pruebas
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar PHP en la versión deseada
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Cambia la versión si necesitas otra

      # Paso 3: Instalar las dependencias con Composer
      - name: Install dependencies
        run: composer install

      # Paso 4: Ejecutar las pruebas con PHPUnit
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit tests
